/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import model.Payment;
import model.UsageLog;

import java.awt.event.ActionEvent;
import java.awt.Font;
import java.awt.GridBagConstraints;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

import manager.ComputerDao;
import manager.PaymentDao;
import manager.ServiceLogDao;
import manager.UsageLogDao;

/**
 *
 * @author ADMIN
 */
public class PaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form Tramay
     */
	public UsageLog _usageLog = new UsageLog();
	public DateTimeFormatter formatter; 
	public Payment _payment = new Payment();
    public PaymentUI(UsageLog usageLog) {
    	
        this._usageLog = usageLog;
        formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        initComponents(); 
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String startTimeStr = inputFormat.format(_usageLog.getStartTime());
        LocalDateTime startTime = LocalDateTime.parse(startTimeStr, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        lbgiovao.setText(formatter.format(startTime));

        // Lấy giờ hiện tại (giờ ra)
        LocalDateTime endTime = LocalDateTime.now();
        lbgiora.setText(formatter.format(endTime));

        // Tính toán Duration
        Duration duration = Duration.between(startTime, endTime);
        
        double durationHours = duration.toMinutes() / 60.0;
        BigDecimal durationHours1 = new BigDecimal(Double.toString(durationHours)); // Chuyển đổi double sang BigDecimal (quan trọng)
        durationHours1 = durationHours1.setScale(2, RoundingMode.HALF_UP); // Làm tròn đến 2 chữ số thập phân, HALF_UP là làm tròn 0.5 lên 1

        double roundedNumber = durationHours1.doubleValue(); // Lấy giá trị double đã được làm tròn

        System.out.println(roundedNumber);

        // Tính toán giờ, phút, giây
        long seconds = duration.getSeconds();
        long minutes = seconds / 60;
        long hours = minutes / 60;
        minutes %= 60;
        seconds %= 60;

        String formattedDuration = String.format("%02d:%02d:%02d", hours, minutes, seconds);
        lbtiengio.setText(String.valueOf(formattedDuration));
        
        
        double computerPrice;
        computerPrice = ComputerDao.getComputerPriceByComputerId(_usageLog.getComputerId());
        double tiengio = computerPrice*roundedNumber;
        BigDecimal bd = new BigDecimal(Double.toString(tiengio));
        bd = bd.setScale(1, RoundingMode.HALF_UP);
        tiengio = bd.doubleValue();
        lbthanhtiengio.setText(String.valueOf(tiengio));
        	
        double servicePrice;
        servicePrice = ServiceLogDao.getServicePriceByUsageId(_usageLog.getId());
        lbtiendichvu.setText(String.valueOf(servicePrice));
        
        double total = tiengio+servicePrice;
        lbtongsotien.setText(String.valueOf(total));
        
        this._payment.setUsageId(_usageLog.getId());
        this._payment.setAmount(total);
       
	
        ZoneId zoneId = ZoneId.systemDefault();
        GregorianCalendar calendar = GregorianCalendar.from(endTime.atZone(zoneId));
        Date paymentDate = calendar.getTime();
        this._payment.setPaymentDate(paymentDate);
        
    }
    	
    	public PaymentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        lbtiendichvu = new javax.swing.JLabel();
        lbtiengio = new javax.swing.JLabel();
        lbtongsotien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbthanhtiengio = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		handleActionPayment();
        		gui.Main gm = new gui.Main();
        			gm.show();
        			dispose();
        	}
        });
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        txt = new javax.swing.JLabel();
        lbgiovao123 = new javax.swing.JLabel();
        lbgiovao123.setHorizontalAlignment(SwingConstants.TRAILING);
        lbgiovao = new javax.swing.JLabel();
        lbgiora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Tổng số tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(label1, gridBagConstraints);

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("Số giờ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(label2, gridBagConstraints);

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("Số tiền dịch vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(label3, gridBagConstraints);

        lbtiendichvu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbtiendichvu.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbtiendichvu, gridBagConstraints);

        lbtiengio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbtiengio, gridBagConstraints);

        lbtongsotien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbtongsotien.setToolTipText("");
        lbtongsotien.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbtongsotien, gridBagConstraints);

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
        jLabel1.setText("Thành tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        lbthanhtiengio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 47;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbthanhtiengio, gridBagConstraints);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(51, 255, 51));
        label4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label4.setText("Thanh toán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 526;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        getContentPane().add(label4, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); 
        jButton1.setText("Thanh toán");
        jButton1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); 
        jButton2.setText("Quay lại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButton2, gridBagConstraints);

        txt.setFont(new Font("Segoe UI", Font.BOLD, 24)); 
        txt.setText("Giờ ra");
        txt.setToolTipText("");
        gridBagConstraints_1 = new java.awt.GridBagConstraints();
        gridBagConstraints_1.gridheight = 2;
        gridBagConstraints_1.gridx = 6;
        gridBagConstraints_1.gridy = 1;
        gridBagConstraints_1.ipadx = 55;
        gridBagConstraints_1.ipady = 5;
        gridBagConstraints_1.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(txt, gridBagConstraints_1);

        lbgiovao123.setFont(new Font("Segoe UI", Font.BOLD, 24)); 
        lbgiovao123.setText("Giờ vào");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbgiovao123, gridBagConstraints);

        lbgiovao.setFont(new Font("Segoe UI", Font.BOLD, 12)); 
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.ipady = 43;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbgiovao, gridBagConstraints);

        lbgiora.setFont(new Font("Segoe UI", Font.BOLD, 12)); 
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.ipady = 43;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lbgiora, gridBagConstraints);

        pack();
    }// </editor-fold>                        
    public void handleActionPayment() {
    	boolean paymentInsert = PaymentDao.insertPayment(_payment);
    	boolean updateStatus = ComputerDao.updateComputerStatus(_usageLog.getComputerId(), 2);
    	
    	
    	boolean updateEndtime = UsageLogDao.updateEndtimeByUsageId(_usageLog.getId(), _payment.getPaymentDate());
        if (paymentInsert && updateStatus && updateEndtime) {
            JOptionPane.showMessageDialog(null, "Thanh toán thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Thanh toán thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }	
    	
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel lbgiora;
    private javax.swing.JLabel lbgiovao;
    private javax.swing.JLabel lbgiovao123;
    private javax.swing.JLabel lbthanhtiengio;
    private javax.swing.JLabel lbtiendichvu;
    private javax.swing.JLabel lbtiengio;
    private javax.swing.JLabel lbtongsotien;
    private javax.swing.JLabel txt;
    private GridBagConstraints gridBagConstraints_1;
    // End of variables declaration                   
}
