/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import manager.CustomerDao;
import manager.ServiceDao;
import model.Customer;
import model.ServiceLog;
import model.UsageLog;
import manager.ServiceLogDao;
import java.awt.Dimension;
import javax.swing.ScrollPaneConstants;
import javax.swing.JButton;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.SwingConstants;

/**
 *
 * @author ADMIN
 */
public class ServiceLogUI extends javax.swing.JFrame {

    /**
     * Creates new form Dichvu
     */
	public UsageLog _usageLog = new UsageLog();
	
    public ServiceLogUI(UsageLog usageLog) {
    	
        this._usageLog = usageLog;
        initComponents();
        tenMay.setText(usageLog.getComputerName());
        nguoiDung.setText(usageLog.getCustomerName());
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	    String formattedDate = dateFormat.format(usageLog.getStartTime());
	    ngayGio.setText(formattedDate); 
	    loadService();
    }
 
    public ServiceLogUI() {
    	loadService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nguoiDung = new javax.swing.JLabel();
        ngayGio = new javax.swing.JLabel();
        tenMay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        bangSoLuong = new javax.swing.JTable();
        dichVu = new javax.swing.JButton();	
        dichVu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
            		Service dv = new Service(_usageLog.getId(), new Runnable() {
                        @Override
                        public void run() {
                            loadService();  
                        }
                    });
            		dv.show();
        	}
        });
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nguoiDung.setIcon(new ImageIcon("C:\\Users\\ADMIN\\Downloads\\123414.jpg")); // NOI18N
        nguoiDung.setText("NGUOIDUNG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(52, 45, 5, 5);
        getContentPane().add(nguoiDung, gridBagConstraints);

        ngayGio.setIcon(new ImageIcon("C:\\Users\\ADMIN\\Downloads\\calendar-clock-icon.png")); // NOI18N
        ngayGio.setText("NGAYGIO");
        ngayGio.setMaximumSize(new java.awt.Dimension(101, 27));
        ngayGio.setMinimumSize(new java.awt.Dimension(101, 27));
        ngayGio.setPreferredSize(new Dimension(170, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(52, 74, 5, 5);
        getContentPane().add(ngayGio, gridBagConstraints);

        tenMay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenMay.setText("TENMAY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(10, 89, 5, 5);
        getContentPane().add(tenMay, gridBagConstraints);

        bangSoLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Dịch vụ", "Số lượng", "Thành tiền"
            }
        ) {
        boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(bangSoLuong);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 554;
        gridBagConstraints.ipady = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(27, 10, 5, 12);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        dichVu.setText("THÊM DỊCH VỤ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(18, 44, 46, 5);
        getContentPane().add(dichVu, gridBagConstraints);
        
        jButton1.setText("QUAY LẠI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 35, 46, 5);
        getContentPane().add(jButton1, gridBagConstraints);
        
        thanhToan = new JButton();
        thanhToan.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		PaymentUI pm = new PaymentUI(_usageLog);
        		pm.show();
        	}
        });
        thanhToan.setText("THANH TOÁN");
        GridBagConstraints gbc_thanhToan = new GridBagConstraints();
        gbc_thanhToan.insets = new Insets(18, 44, 46, 5);
        gbc_thanhToan.gridx = 4;
        gbc_thanhToan.gridy = 3;
        getContentPane().add(thanhToan, gbc_thanhToan);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
    		ListComputer2 ls = new ListComputer2();
    		ls.show();
    		dispose();
    }                                        

    private void loadService() {
        DefaultTableModel table = (DefaultTableModel) bangSoLuong.getModel();
        table.setRowCount(0);
        List<ServiceLog> listServiceLog = ServiceLogDao.getAllServiceLogsByUsageId(_usageLog.getId());
        for (model.ServiceLog sr : listServiceLog) {
        	table.addRow(new Object[]{
                sr.getServiceName(),
                sr.getQuantity(),
                sr.getTotal()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceLogUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable bangSoLuong;
    private javax.swing.JButton dichVu;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ngayGio;
    private javax.swing.JLabel nguoiDung;
    private javax.swing.JLabel tenMay;
    private JButton thanhToan;
    // End of variables declaration                   
}
